### ISSUE TITLE
ajax-adapter should self-register with Breeze?

### ISSUE THREAD

**Issue by wardbell** [jdanyow/aurelia-breeze#1]
It is conventional for the file that defines a new adapter to "self-register" that adapter with Breeze ... a step that must be taken eventually anyway.

Here is the line I was expecting to see, perhaps near the bottom of the file:

```
breeze.config.registerAdapter("ajax", AjaxAdapter);
```

And having done that, there would be no need to register it as you do later in [_index.js_](https://github.com/jdanyow/aurelia-breeze/blob/master/src/index.js#L16) and **no reason to export `AjaxAdapter`** at all.

Any reason you went this other way?

Perhaps you were thinking testing? Well the standard way any consumer of breeze would access this adapter is by requesting it from Breeze

```
var ajaxAdapter = breeze.config.getAdapterInstance("ajax", 'aurelia'); // get the current instance
var AjaxAdapter = breeze.config.getAdapter("ajax", 'aurelia'); // get the constructor function (rare)
```

That's how I'd do it in my tests ... in part because in tests I want to follow as closely as I can the way I expect developers to work with this component.

Thoughts?

**Comment by jdanyow** [comment]
No really good reason, I basically put all the wiring-up/registration related stuff in one spot, the index.js.  I don't see the benefit of not exporting the AjaxAdapter class.  Exporting enables direct testing as well as inheritance scenarios, etc.  Is there a reason why exporting this is bad?  I dislike running into issues reusing stuff because everything is private/internal/sealed.

I think your suggestion to do more of an integration style test with the ajax adapter makes a lot of sense.  Will make that change.

**Comment by wardbell** [comment]
I'm just explaining the convention breeze follows. The thinking is that self registration means one fewer configuration for the consumer to remember.

I don't mind the test practice I showed above. Not much of a burden nor much of an integration IMO
